### ISSUE TITLE
Add CI using GitHub Actions

### ISSUE THREAD

**Issue by stvdwtt** [ORNL/Thermo4PFM#57]
From @streeve tells me that setting up CI with GitHub Actions is pretty easy and is worth looking into.

**Comment by streeve** [comment]
If you give me push access I can add a draft

**Comment by stvdwtt** [comment]
You're a good man, @streeve. @jeanlucf22, I don't think I have administrator rights to give Sam push access. Any objections to adding CI?

**Comment by jeanlucf22** [comment]
just made @streeve an admin. No objection to adding CI!
